#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -z "$1" ]; then
    OS_PLATFORM_ARG="darwin linux windows"
else
    OS_PLATFORM_ARG=$1
fi

if [ -z "$2" ]; then
    OS_ARCH_ARG="386 amd64"
else
    OS_ARCH_ARG=$2
fi

rm oauth2util-*
docker build -t oauth2util . 1>&2

for GOOS in $OS_PLATFORM_ARG; do
  for GOARCH in $OS_ARCH_ARG; do
    echo $GOOS $GOARCH
    case $GOOS in
      windows) SUFFIX=".exe" ;;
      *) SUFFIX="" ;;
    esac
    docker run -e GOOS=$GOOS -e GOARCH=$GOARCH oauth2util /bin/bash -c "go build -o oauth2util-$GOOS-$GOARCH$SUFFIX 1>&2 && tar -czf - oauth2util-*" | tar -xzf -
  done
done
